version: '3.8'

services:
  # Backend Service (NestJS)
  backend:
    build:
      context: ./phishing_simulator_api
    container_name: phishing_simulator_backend
    ports:
      - "3000:3000"  # Expose port 3000 for backend API
    networks:
      - phishing_network
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./phishing_simulator_frontend
    container_name: phishing_simulator_frontend
    ports:
      - "3001:3001"  # Expose port 3001 for frontend
    networks:
      - phishing_network
  # MongoDB Service (for backend data storage)
  mongo:
    image: mongo:latest
    container_name: phishing_simulator_mongo
    ports:
      - "27017:27017"  # Expose MongoDB default port
    networks:
      - phishing_network
    volumes:
      - ./data/db:/data/db  # Persistent storage for MongoDB data

networks:
  phishing_network:
    driver: bridge
