export enum TokenTypeEnum {
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  VERIFY_ACCOUNT = 'VERIFY_ACCOUNT',
  RESET_PASSWORD = 'RESET_PASSWORD',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  AUTH = 'AUTH',
  REFRESH = 'REFRESH',
}
